[no-cd]
default:
    uv run python source_download.py frignhd_pyrenees
    uv run python source_bounds.py frignhd_pyrenees
    uv run python source_polygonize.py frignhd_pyrenees 32
    uv run python source_create_tarball.py frignhd_pyrenees
